// Tickets module exports
export * from './types';
export * from './services/tickets-service';
export * from './hooks/useTickets';
export * from './components/dashboard/SupportDashboard';
export * from './components/ticket-list/TicketList';
export * from './components/ticket-detail/TicketDetailView';
export * from './components/create-ticket/CreateTicketForm';
export * from './components/knowledge-base/KnowledgeBase';
export * from './components/analytics/SupportAnalytics';
