// Customer module exports
export * from './types';
export * from './services/customer-service';
export * from './hooks/useCustomers';
export * from './components/dashboard/CustomerDashboard';
export * from './components/dashboard/CustomerStats';
export * from './components/list/CustomerList';
export * from './components/filters/CustomerFilters';
export * from './components/forms/CreateCustomerForm';
