"""Add extended customer models, OAuth, 2FA, and API key models

Revision ID: 7fbe30f0c3ed
Revises: 
Create Date: 2025-07-23 12:26:11.160384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fbe30f0c3ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('address', sa.String(length=500), nullable=True))
    op.drop_column('customers', 'zip_code')
    op.drop_column('customers', 'state')
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'country')
    op.drop_column('customers', 'street_1')
    op.drop_column('customers', 'street_2')
    op.drop_column('customers', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('category', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('street_2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('street_1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('zip_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('customers', 'address')
    # ### end Alembic commands ###
